CUB3D_SOURCES := main.c \
				 main_utils.c \
				 app/manage_app.c \
				 app/hooks.c \
				 app/mouse.c \
				 vector/vector.c \
				 vector/vector_scalar.c \
				 display/display.c \
				 display/minimap.c \
				 raycast/raycaster.c \
				 raycast/texture.c \
				 raycast/utils.c \
				 TAS/tas.c \
				 init.c \
				 input.c \
				 image.c \
				 prep_exec.c \
				 parsing/check_file_name.c \
 				 parsing/flood_fill.c \
				 parsing/parse_color.c \
				 parsing/parse_file.c \
				 parsing/parse_map.c \
				 parsing/parse_texture.c \
				 parsing/parsing_utils.c \
